/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Members;
import Utilities.ReadWrite;
import java.awt.Color;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.NotSerializableException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ppunme
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    //input and output file
    private static String fileName = "Members.bin";
    
    public static ArrayList<Members> list = new ArrayList<Members>();
    
    private static int numMembers = 0; //count total no. of members records on file (to set the next ID)
    
    //open OutputFile
    private static FileOutputStream fos; 
    private static ObjectOutputStream oos; 
    
    Color myColor = new Color(163, 186, 195); 
    
    public MainMenu() {
        initComponents();
        
        this.setTitle("Main Menu");
        this.setBounds(530, 100, 540, 560); // (x,y,width,height)
        
        //pnlAdd.setBorder(BorderFactory.createLineBorder(myColor, 2));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAll = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        lblHead1 = new javax.swing.JLabel();
        lblHead2 = new javax.swing.JLabel();
        btnBackup = new javax.swing.JPanel();
        icBackup = new javax.swing.JLabel();
        lblBackup = new javax.swing.JLabel();
        btnRestore = new javax.swing.JPanel();
        icRestore = new javax.swing.JLabel();
        lblRestore = new javax.swing.JLabel();
        btnAddMember = new javax.swing.JPanel();
        lblAddMember = new javax.swing.JLabel();
        icAddMember = new javax.swing.JLabel();
        btnSearch = new javax.swing.JPanel();
        icSearch = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        btnAddBroker = new javax.swing.JPanel();
        icAddBroker = new javax.swing.JLabel();
        lblAddBroker = new javax.swing.JLabel();
        btnHelp = new javax.swing.JPanel();
        icHelp = new javax.swing.JLabel();
        lblHelp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlAll.setBackground(new java.awt.Color(255, 255, 255));
        pnlAll.setForeground(new java.awt.Color(66, 75, 84));

        pnlHead.setBackground(new java.awt.Color(163, 186, 195));

        lblHead1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblHead1.setForeground(new java.awt.Color(255, 255, 255));
        lblHead1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHead1.setText("Health Insurance");

        lblHead2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lblHead2.setForeground(new java.awt.Color(255, 255, 255));
        lblHead2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHead2.setText("Member Registration");

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHead2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHead1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(lblHead1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHead2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        btnBackup.setBackground(new java.awt.Color(234, 235, 237));
        btnBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackupMousePressed(evt);
            }
        });

        icBackup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnBackup.png"))); // NOI18N

        lblBackup.setForeground(new java.awt.Color(66, 75, 84));
        lblBackup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackup.setText("Backup");

        javax.swing.GroupLayout btnBackupLayout = new javax.swing.GroupLayout(btnBackup);
        btnBackup.setLayout(btnBackupLayout);
        btnBackupLayout.setHorizontalGroup(
            btnBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnBackupLayout.setVerticalGroup(
            btnBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackupLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(icBackup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblBackup)
                .addContainerGap())
        );

        btnRestore.setBackground(new java.awt.Color(234, 235, 237));
        btnRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRestoreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRestoreMousePressed(evt);
            }
        });

        icRestore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnRestore.png"))); // NOI18N

        lblRestore.setForeground(new java.awt.Color(66, 75, 84));
        lblRestore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestore.setText("Restore");

        javax.swing.GroupLayout btnRestoreLayout = new javax.swing.GroupLayout(btnRestore);
        btnRestore.setLayout(btnRestoreLayout);
        btnRestoreLayout.setHorizontalGroup(
            btnRestoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRestoreLayout.createSequentialGroup()
                .addComponent(icRestore, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblRestore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnRestoreLayout.setVerticalGroup(
            btnRestoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRestoreLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(icRestore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRestore)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnAddMember.setBackground(new java.awt.Color(234, 235, 237));
        btnAddMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMemberMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddMemberMousePressed(evt);
            }
        });

        lblAddMember.setForeground(new java.awt.Color(66, 75, 84));
        lblAddMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddMember.setText("Add Member");

        icAddMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icAddMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAdd.png"))); // NOI18N

        javax.swing.GroupLayout btnAddMemberLayout = new javax.swing.GroupLayout(btnAddMember);
        btnAddMember.setLayout(btnAddMemberLayout);
        btnAddMemberLayout.setHorizontalGroup(
            btnAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddMember, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(icAddMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnAddMemberLayout.setVerticalGroup(
            btnAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddMemberLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(icAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddMember)
                .addContainerGap())
        );

        btnSearch.setBackground(new java.awt.Color(234, 235, 237));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearchMousePressed(evt);
            }
        });

        icSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnSearch.png"))); // NOI18N

        lblSearch.setForeground(new java.awt.Color(66, 75, 84));
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("Search");

        javax.swing.GroupLayout btnSearchLayout = new javax.swing.GroupLayout(btnSearch);
        btnSearch.setLayout(btnSearchLayout);
        btnSearchLayout.setHorizontalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnSearchLayout.setVerticalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(icSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSearch)
                .addContainerGap())
        );

        btnAddBroker.setBackground(new java.awt.Color(234, 235, 237));
        btnAddBroker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddBrokerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddBrokerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddBrokerMousePressed(evt);
            }
        });

        icAddBroker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icAddBroker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAddBroker.png"))); // NOI18N

        lblAddBroker.setForeground(new java.awt.Color(66, 75, 84));
        lblAddBroker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddBroker.setText("Add Broker");

        javax.swing.GroupLayout btnAddBrokerLayout = new javax.swing.GroupLayout(btnAddBroker);
        btnAddBroker.setLayout(btnAddBrokerLayout);
        btnAddBrokerLayout.setHorizontalGroup(
            btnAddBrokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddBrokerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAddBrokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icAddBroker, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lblAddBroker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnAddBrokerLayout.setVerticalGroup(
            btnAddBrokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddBrokerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(icAddBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddBroker)
                .addContainerGap())
        );

        btnHelp.setBackground(new java.awt.Color(234, 235, 237));
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHelpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHelpMousePressed(evt);
            }
        });

        icHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnHelp.png"))); // NOI18N

        lblHelp.setForeground(new java.awt.Color(66, 75, 84));
        lblHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelp.setText("Help");

        javax.swing.GroupLayout btnHelpLayout = new javax.swing.GroupLayout(btnHelp);
        btnHelp.setLayout(btnHelpLayout);
        btnHelpLayout.setHorizontalGroup(
            btnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnHelpLayout.setVerticalGroup(
            btnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHelpLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(icHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHelp)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAllLayout = new javax.swing.GroupLayout(pnlAll);
        pnlAll.setLayout(pnlAllLayout);
        pnlAllLayout.setHorizontalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAllLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBroker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAllLayout.createSequentialGroup()
                        .addComponent(btnAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        pnlAllLayout.setVerticalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllLayout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBroker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMemberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMemberMousePressed
        AddSingle addSingle = new AddSingle(this, list);
        this.setVisible(false);	
    }//GEN-LAST:event_btnAddMemberMousePressed

    private void btnBackupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMousePressed
        try{
            writeData(list);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());	
        }	
        JOptionPane.showMessageDialog(null, "All Member records stored to file \"Members.bin\"");
        //System.exit(0);  
    }//GEN-LAST:event_btnBackupMousePressed

    private void btnHelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpMousePressed

    private void btnRestoreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestoreMousePressed
        try{
            readData();
            JOptionPane.showMessageDialog(null, list.size() + " Member records have been loaded from file");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());	
        }
    }//GEN-LAST:event_btnRestoreMousePressed

    private void btnAddMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMemberMouseEntered
        setColor(btnAddMember);
        btnAddMember.setToolTipText("Add Family Membership details to the system");
    }//GEN-LAST:event_btnAddMemberMouseEntered

    private void btnHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseEntered
        setColor(btnHelp);
    }//GEN-LAST:event_btnHelpMouseEntered

    private void btnBackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseEntered
        setColor(btnBackup);
    }//GEN-LAST:event_btnBackupMouseEntered

    private void btnRestoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestoreMouseEntered
        setColor(btnRestore);
    }//GEN-LAST:event_btnRestoreMouseEntered

    private void btnAddMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMemberMouseExited
        resetColor(btnAddMember);
    }//GEN-LAST:event_btnAddMemberMouseExited

    private void btnHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseExited
        resetColor(btnHelp);
    }//GEN-LAST:event_btnHelpMouseExited

    private void btnBackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseExited
        resetColor(btnBackup);
    }//GEN-LAST:event_btnBackupMouseExited

    private void btnRestoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestoreMouseExited
        resetColor(btnRestore);
    }//GEN-LAST:event_btnRestoreMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Font fn = null;
        try{
            fn = Font.createFont(Font.TRUETYPE_FONT,getClass().getResourceAsStream("../Font/Roboto-Regular.ttf"));
            Font f1 = fn.deriveFont(Font.PLAIN,40);
            Font f2 = fn.deriveFont(Font.PLAIN,22);
            Font f3 = fn.deriveFont(Font.PLAIN,14);
            
            lblHead1.setFont(f1);
            lblHead2.setFont(f2);
            //lblAddMember.setFont(f3);
            lblAddBroker.setFont(f3);
            lblAddMember.setFont(f3);
            lblSearch.setFont(f3);
            lblHelp.setFont(f3);
            lblBackup.setFont(f3);
            lblRestore.setFont(f3);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnAddBrokerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBrokerMousePressed
        //AddSingle addSingleFrame = new AddSingle(this, list);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddBrokerMousePressed

    private void btnAddBrokerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBrokerMouseExited
        resetColor(btnAddBroker);
    }//GEN-LAST:event_btnAddBrokerMouseExited

    private void btnAddBrokerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBrokerMouseEntered
        setColor(btnAddBroker);
        btnAddBroker.setToolTipText("Add Insurance broker details to the system");
    }//GEN-LAST:event_btnAddBrokerMouseEntered

    private void btnSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMousePressed
        /*String output = "MEMBER DETAILS\n\n";
        list = readData();

        for(Members obj : list){
            output += obj + "\n";
        }
        JOptionPane.showMessageDialog(null, output);*/
        
        SearchForm searchForm = new SearchForm(this, list);
        this.setVisible(false);	
        
    }//GEN-LAST:event_btnSearchMousePressed

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        resetColor(btnSearch);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        setColor(btnSearch);
    }//GEN-LAST:event_btnSearchMouseEntered

    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(163,186,195));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(238,238,238));
    }
    
    public static void writeData(ArrayList<Members> list){
        
        try{
            ReadWrite.writeData(fileName, list);
        }
        catch(FileNotFoundException fnfEx){
            System.err.println("Problem with the binary file");
        }
        catch(ClassNotFoundException cnfEx){
            System.err.println("Problem with the Members class");
        }
        catch(NotSerializableException nsEx){
            System.err.println("A class has not been serialised");
        }
        catch (IOException ioEx){
            System.err.println("Issue(s) with saving data to file");
        }
        
    }
    
    public static ArrayList<Members> readData(){
        
        ArrayList<Members> list = new ArrayList<>();
        
        try{
           list = ReadWrite.readData(fileName);
        }
        catch(FileNotFoundException fnfEx){
            System.err.println("Problem with the Members.bin file");
            JOptionPane.showMessageDialog(null, "File \"Members.bin\" will be created");
        }
        catch(ClassNotFoundException cnfEx){
            System.err.println("Patient class does not exist");
        }
        catch(NotSerializableException nsEx){
            System.err.println("A class has not been serialised");
        }
        catch(IOException ioEx){
            System.err.println("Problem with reading data from file");
        }
        return list;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAddBroker;
    private javax.swing.JPanel btnAddMember;
    private javax.swing.JPanel btnBackup;
    private javax.swing.JPanel btnHelp;
    private javax.swing.JPanel btnRestore;
    private javax.swing.JPanel btnSearch;
    private javax.swing.JLabel icAddBroker;
    private javax.swing.JLabel icAddMember;
    private javax.swing.JLabel icBackup;
    private javax.swing.JLabel icHelp;
    private javax.swing.JLabel icRestore;
    private javax.swing.JLabel icSearch;
    private javax.swing.JLabel lblAddBroker;
    private javax.swing.JLabel lblAddMember;
    private javax.swing.JLabel lblBackup;
    private javax.swing.JLabel lblHead1;
    private javax.swing.JLabel lblHead2;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblRestore;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JPanel pnlHead;
    // End of variables declaration//GEN-END:variables
}
