/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Agent;
import Classes.Members;
import Utilities.ReadWrite;
import java.awt.Color;
import java.awt.Font;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.NotSerializableException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ppunme
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    //input and output file
    private static String fileName = "Members.bin";
    
    public static ArrayList<Members> list = new ArrayList<Members>();
    public static ArrayList<Agent> agentList = new ArrayList<Agent>();
    public static ArrayList<Members> restoredList = new ArrayList<>();
    private static int numMembers = 0; //count total no. of members records on file (to set the next ID)
    
    //open OutputFile
    private static FileOutputStream fos; 
    private static ObjectOutputStream oos; 
    
    Color myColor = new Color(163, 186, 195); 
    
    public MainMenu() {
        initComponents();
        
        this.setTitle("Main Menu");
        this.setBounds(500, 100, 525, 570); // (x,y,width,height)
        
        //read contents of file on loading the main menu GUI
        readFile();
        JOptionPane.showMessageDialog(null, restoredList.size() + " Member records have been loaded from file");
        System.out.println(list);
        System.out.println("Restored List: " + restoredList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAll = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        lblHead1 = new javax.swing.JLabel();
        lblHead2 = new javax.swing.JLabel();
        btnBackup = new javax.swing.JPanel();
        icBackup = new javax.swing.JLabel();
        lblBackup = new javax.swing.JLabel();
        btnRestore = new javax.swing.JPanel();
        icRestore = new javax.swing.JLabel();
        lblRestore = new javax.swing.JLabel();
        btnAddMember = new javax.swing.JPanel();
        lblAddFamily = new javax.swing.JLabel();
        icAddFamily = new javax.swing.JLabel();
        btnSearch = new javax.swing.JPanel();
        icSearch = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        btnAddAgent = new javax.swing.JPanel();
        icAddSingle = new javax.swing.JLabel();
        lblAddSingle = new javax.swing.JLabel();
        btnHelp = new javax.swing.JPanel();
        icHelp = new javax.swing.JLabel();
        lblHelp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBackup1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlAll.setBackground(new java.awt.Color(234, 234, 234));
        pnlAll.setForeground(new java.awt.Color(66, 75, 84));

        pnlHead.setBackground(new java.awt.Color(34, 70, 96));

        lblHead1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblHead1.setForeground(new java.awt.Color(255, 255, 255));
        lblHead1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHead1.setText("Health Insurance");

        lblHead2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lblHead2.setForeground(new java.awt.Color(255, 255, 255));
        lblHead2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHead2.setText("Member Registration");

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeadLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblHead2))
                    .addGroup(pnlHeadLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblHead1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblHead1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHead2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnBackup.setBackground(new java.awt.Color(255, 255, 255));
        btnBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackupMousePressed(evt);
            }
        });

        icBackup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-database-50orange.png"))); // NOI18N

        lblBackup.setForeground(new java.awt.Color(102, 102, 102));
        lblBackup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackup.setText("Backup");

        javax.swing.GroupLayout btnBackupLayout = new javax.swing.GroupLayout(btnBackup);
        btnBackup.setLayout(btnBackupLayout);
        btnBackupLayout.setHorizontalGroup(
            btnBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icBackup, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnBackupLayout.setVerticalGroup(
            btnBackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBackupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icBackup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBackup)
                .addGap(12, 12, 12))
        );

        btnRestore.setBackground(new java.awt.Color(255, 255, 255));
        btnRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRestoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRestoreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRestoreMousePressed(evt);
            }
        });

        icRestore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-restart-purple.png"))); // NOI18N

        lblRestore.setForeground(new java.awt.Color(102, 102, 102));
        lblRestore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestore.setText("Restore");

        javax.swing.GroupLayout btnRestoreLayout = new javax.swing.GroupLayout(btnRestore);
        btnRestore.setLayout(btnRestoreLayout);
        btnRestoreLayout.setHorizontalGroup(
            btnRestoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRestoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRestore, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(icRestore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnRestoreLayout.setVerticalGroup(
            btnRestoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRestoreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRestore)
                .addGap(12, 12, 12))
        );

        btnAddMember.setBackground(new java.awt.Color(255, 255, 255));
        btnAddMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMemberMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddMemberMousePressed(evt);
            }
        });

        lblAddFamily.setForeground(new java.awt.Color(102, 102, 102));
        lblAddFamily.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddFamily.setText("Add Member");

        icAddFamily.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icAddFamily.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-green.png"))); // NOI18N
        icAddFamily.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout btnAddMemberLayout = new javax.swing.GroupLayout(btnAddMember);
        btnAddMember.setLayout(btnAddMemberLayout);
        btnAddMemberLayout.setHorizontalGroup(
            btnAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddMemberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icAddFamily, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lblAddFamily, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnAddMemberLayout.setVerticalGroup(
            btnAddMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddMemberLayout.createSequentialGroup()
                .addComponent(icAddFamily, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddFamily)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearchMousePressed(evt);
            }
        });

        icSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-search-50blue.png"))); // NOI18N
        icSearch.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblSearch.setForeground(new java.awt.Color(102, 102, 102));
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("Search");

        javax.swing.GroupLayout btnSearchLayout = new javax.swing.GroupLayout(btnSearch);
        btnSearch.setLayout(btnSearchLayout);
        btnSearchLayout.setHorizontalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnSearchLayout.setVerticalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addComponent(icSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        btnAddAgent.setBackground(new java.awt.Color(255, 255, 255));
        btnAddAgent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAddAgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddAgentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddAgentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddAgentMousePressed(evt);
            }
        });

        icAddSingle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icAddSingle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-business-red.png"))); // NOI18N
        icAddSingle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblAddSingle.setForeground(new java.awt.Color(102, 102, 102));
        lblAddSingle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddSingle.setText("Add Agent");

        javax.swing.GroupLayout btnAddAgentLayout = new javax.swing.GroupLayout(btnAddAgent);
        btnAddAgent.setLayout(btnAddAgentLayout);
        btnAddAgentLayout.setHorizontalGroup(
            btnAddAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAddAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icAddSingle, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lblAddSingle, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnAddAgentLayout.setVerticalGroup(
            btnAddAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddAgentLayout.createSequentialGroup()
                .addComponent(icAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        btnHelp.setBackground(new java.awt.Color(255, 255, 255));
        btnHelp.setForeground(new java.awt.Color(255, 255, 255));
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHelpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHelpMousePressed(evt);
            }
        });

        icHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-help-50grey.png"))); // NOI18N
        icHelp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblHelp.setForeground(new java.awt.Color(102, 102, 102));
        lblHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelp.setText("Help");

        javax.swing.GroupLayout btnHelpLayout = new javax.swing.GroupLayout(btnHelp);
        btnHelp.setLayout(btnHelpLayout);
        btnHelpLayout.setHorizontalGroup(
            btnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnHelpLayout.setVerticalGroup(
            btnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHelpLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(icHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHelp)
                .addGap(12, 12, 12))
        );

        jPanel1.setBackground(new java.awt.Color(57, 51, 59));

        lblBackup1.setForeground(new java.awt.Color(255, 255, 255));
        lblBackup1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackup1.setText("Exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBackup1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackup1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlAllLayout = new javax.swing.GroupLayout(pnlAll);
        pnlAll.setLayout(pnlAllLayout);
        pnlAllLayout.setHorizontalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAllLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pnlAllLayout.setVerticalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllLayout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMemberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMemberMousePressed
        AddMember addMember = new AddMember(this, list);
        this.setVisible(false);	
    }//GEN-LAST:event_btnAddMemberMousePressed

    private void btnBackupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMousePressed

        try{
            ReadWrite.writeData(fileName, list);
        } catch(FileNotFoundException fnfEx){
            System.err.println("Problem with the Members.bin file");
            JOptionPane.showMessageDialog(null, "File \"Members.bin\" will be created");
        } catch(ClassNotFoundException cnfEx){
            System.err.println("Patient class does not exist");
        } catch(NotSerializableException nsEx){
            System.err.println("A class has not been serialised");
        }
        catch(IOException ioEx){
            System.err.println("Problem with reading data from file");
        }
    }//GEN-LAST:event_btnBackupMousePressed

    private void btnHelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpMousePressed

    private void btnRestoreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestoreMousePressed
        try{
            readFile();
            JOptionPane.showMessageDialog(null, restoredList.size() + " Member records have been loaded from file");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());	
        }
    }//GEN-LAST:event_btnRestoreMousePressed

    private void btnAddMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMemberMouseEntered
        setColor(btnAddMember);
        btnAddMember.setToolTipText("Add Family Membership details to the system");
    }//GEN-LAST:event_btnAddMemberMouseEntered

    private void btnHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseEntered
        setColor(btnHelp);
    }//GEN-LAST:event_btnHelpMouseEntered

    private void btnBackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseEntered
        setColor(btnBackup);
    }//GEN-LAST:event_btnBackupMouseEntered

    private void btnRestoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestoreMouseEntered
        setColor(btnRestore);
    }//GEN-LAST:event_btnRestoreMouseEntered

    private void btnAddMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMemberMouseExited
        resetColor(btnAddMember);
    }//GEN-LAST:event_btnAddMemberMouseExited

    private void btnHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseExited
        resetColor(btnHelp);
    }//GEN-LAST:event_btnHelpMouseExited

    private void btnBackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseExited
        resetColor(btnBackup);
    }//GEN-LAST:event_btnBackupMouseExited

    private void btnRestoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestoreMouseExited
        resetColor(btnRestore);
    }//GEN-LAST:event_btnRestoreMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Font fn = null;
        try{
            fn = Font.createFont(Font.TRUETYPE_FONT,getClass().getResourceAsStream("../Font/Roboto-Regular.ttf"));
            Font f1 = fn.deriveFont(Font.PLAIN,40);
            Font f2 = fn.deriveFont(Font.PLAIN,22);
            Font f3 = fn.deriveFont(Font.PLAIN,14);
            
            lblHead1.setFont(f1);
            lblHead2.setFont(f2);
            //lblAddMember.setFont(f3);
            lblAddSingle.setFont(f3);
            lblAddFamily.setFont(f3);
            lblSearch.setFont(f3);
            lblHelp.setFont(f3);
            lblBackup.setFont(f3);
            lblRestore.setFont(f3);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnAddAgentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAgentMousePressed
        AddAgent addAgent = new AddAgent(this, agentList);
        this.setVisible(false);	
        
    }//GEN-LAST:event_btnAddAgentMousePressed

    private void btnAddAgentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAgentMouseExited
        resetColor(btnAddAgent);
    }//GEN-LAST:event_btnAddAgentMouseExited

    private void btnAddAgentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAgentMouseEntered
        setColor(btnAddAgent);
        btnAddAgent.setToolTipText("Add Insurance broker details to the system");
    }//GEN-LAST:event_btnAddAgentMouseEntered

    private void btnSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMousePressed
       
        SearchForm search = new SearchForm(this);
        this.setVisible(false);	
        
    }//GEN-LAST:event_btnSearchMousePressed

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        resetColor(btnSearch);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        setColor(btnSearch);
    }//GEN-LAST:event_btnSearchMouseEntered

    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(181,177,178)); 
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(255,255,255));
    }
    
    public static ArrayList<Members> readData()
    {
 
        ArrayList<Members> list = new ArrayList<>();
        
        try{
           list = ReadWrite.readData(fileName);
        }
        catch(FileNotFoundException fnfEx){
            System.err.println("Problem with the Members.bin file");
            JOptionPane.showMessageDialog(null, "File \"Members.bin\" will be created");
        }
        catch(ClassNotFoundException cnfEx){
            System.err.println("Patient class does not exist");
        }
        catch(NotSerializableException nsEx){
            System.err.println("A class has not been serialised");
        }
        catch(IOException ioEx){
            System.err.println("Problem with reading data from file");
        }
        return list;
    }
    
    public static void readFile()
    {
        boolean reading = true;
        try
        {
            FileInputStream fiStream = new FileInputStream(fileName);
            ObjectInputStream inStream = new ObjectInputStream(fiStream);

            //while (inStream.readObject() != null)
            //while (inStream.available() != 0)
            //while (inStream.read() != -1) 
            while(reading)
            {			
                restoredList.add((Members)inStream.readObject());
                    
                System.out.println(restoredList);
                numMembers++;
            }
            inStream.close();
        }
        catch(EOFException ex)
        {
            reading = false;
        }
        catch(Exception e)
        {
            reading = false;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAddAgent;
    private javax.swing.JPanel btnAddMember;
    private javax.swing.JPanel btnBackup;
    private javax.swing.JPanel btnHelp;
    private javax.swing.JPanel btnRestore;
    private javax.swing.JPanel btnSearch;
    private javax.swing.JLabel icAddFamily;
    private javax.swing.JLabel icAddSingle;
    private javax.swing.JLabel icBackup;
    private javax.swing.JLabel icHelp;
    private javax.swing.JLabel icRestore;
    private javax.swing.JLabel icSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddFamily;
    private javax.swing.JLabel lblAddSingle;
    private javax.swing.JLabel lblBackup;
    private javax.swing.JLabel lblBackup1;
    private javax.swing.JLabel lblHead1;
    private javax.swing.JLabel lblHead2;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblRestore;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JPanel pnlHead;
    // End of variables declaration//GEN-END:variables
}
